### ISSUE TITLE
Readme should say nupic is python 2.7 only

### ISSUE THREAD

**Issue by david-pfx** [numenta/nupic.torch#34]

**Comment by subutai** [comment]
nupic.torch is python 3.7+

**Comment by lscheinkman** [comment]
@david-pfx This repo is python 3. 
If you mean  https://github.com/numenta/nupic, the README in that repo says python 2.7
https://github.com/numenta/nupic#dependencies

**Comment by david-pfx** [comment]
Fine. Then the README should say so. It's very confusing as an outsider to figure out which goes with what if you don't say.

**Comment by subutai** [comment]
Yes, agreed. We'll make the change.
