### ISSUE TITLE
Unable to run example in Colab

### ISSUE THREAD

**Issue by To3No7** [numenta/nupic.torch#64]
When trying to run your [sparse-cnn example in Colab](https://colab.research.google.com/github/numenta/nupic.torch/blob/master/examples/sparse_cnn.ipynb) there are some version problems that I can not workaround.

With the current installation code:
  !pip install git+https://github.com/numenta/nupic.torch.git#egg=nupic.torch
  !pip install torch torchvision

I get the following output:

Collecting nupic.torch
  Cloning https://github.com/numenta/nupic.torch.git to /tmp/pip-install-b9o0b0it/nupic.torch
  Running command git clone -q https://github.com/numenta/nupic.torch.git /tmp/pip-install-b9o0b0it/nupic.torch
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
    Preparing wheel metadata ... done
Collecting torch==1.4
  Downloading https://files.pythonhosted.org/packages/24/19/4804aea17cd136f1705a5e98a00618cb8f6ccc375ad8bfa437408e09d058/torch-1.4.0-cp36-cp36m-manylinux1_x86_64.whl (753.4MB)
     |████████████████████████████████| 753.4MB 20kB/s 
Building wheels for collected packages: nupic.torch
  Building wheel for nupic.torch (PEP 517) ... done
  Created wheel for nupic.torch: filename=nupic.torch-0.0.1.dev0-cp36-none-any.whl size=28916 sha256=6c142169de358b9e077a6a82ebcbf34ec9a4e1e3529b941cd96e601de1452413
  Stored in directory: /tmp/pip-ephem-wheel-cache-fgj1_5_e/wheels/16/4f/f8/89dd360bad620bcbb6b468e0243812cdfeb76792b4a79b263d
Successfully built nupic.torch
ERROR: torchvision 0.6.0+cu101 has requirement torch==1.5.0, but you'll have torch 1.4.0 which is incompatible.
Installing collected packages: torch, nupic.torch
  Found existing installation: torch 1.5.0+cu101
    Uninstalling torch-1.5.0+cu101:
      Successfully uninstalled torch-1.5.0+cu101
Successfully installed nupic.torch-0.0.1.dev0 torch-1.4.0
Requirement already satisfied: torchvision in /usr/local/lib/python3.6/dist-packages (0.6.0+cu101)
Collecting torch==1.5.0
  Downloading https://files.pythonhosted.org/packages/13/70/54e9fb010fe1547bc4774716f11ececb81ae5b306c05f090f4461ee13205/torch-1.5.0-cp36-cp36m-manylinux1_x86_64.whl (752.0MB)
     |████████████████████████████████| 752.0MB 22kB/s 
Requirement already satisfied: pillow>=4.1.1 in /usr/local/lib/python3.6/dist-packages (from torchvision) (7.0.0)
Requirement already satisfied: numpy in /usr/local/lib/python3.6/dist-packages (from torchvision) (1.18.4)
Requirement already satisfied: future in /usr/local/lib/python3.6/dist-packages (from torch==1.5.0->torchvision) (0.16.0)
ERROR: nupic-torch 0.0.1.dev0 has requirement torch==1.4, but you'll have torch 1.5.0 which is incompatible.
Installing collected packages: torch
  Found existing installation: torch 1.4.0
    Uninstalling torch-1.4.0:
      Successfully uninstalled torch-1.4.0
Successfully installed torch-1.5.0

Then I get a runtime error at
from torchvision import datasets, transforms

"RuntimeError: Detected that PyTorch and torchvision were compiled with different CUDA versions. PyTorch has CUDA Version=10.2 and torchvision has CUDA Version=10.1. Please reinstall the torchvision that matches your PyTorch install."

**Comment by 4onen** [comment]
I believe that this was fixed by https://github.com/numenta/nupic.torch/commit/2bfd59d009b9b123aa32fce4eec58f949ddb13ba

Running the example now, it appears to work just fine.
